config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	resources :plays do
		resources :reviews
	end	
	root 'plays#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
	belongs_to :user
    belongs_to :category
    has_many :reviews

    has_attached_file :play_img, :styles => { :play_index => "250x350>", :play_show => "325x475>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :play_img, :content_type => /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :play
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
 before_action :find_play, only: [:show, :edit, :update, :destroy]

  def index
	 if params[:category].blank?
	  @plays = Play.all.order("created_at DESC")
	 else
	  @category_id = Category.find_by(name: params[:category]).id 
	  @plays = Play.where(:category_id => @category_id).order("created_at DESC")
	end
  end


	def show
		if @play.reviews.blank?
			@average_review = 0
		else
		    @average_review = @play.reviews.average(:rating).round(2)
		end    	
	end	

	def new
	 @play = current_user.plays.build	
	 @categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
	  @play = current_user.plays.build(play_params)
	  @play.category_id = params[:category_id]

		if @play.save
			redirect_to root_path
		else
			render 'new'
		end
	end	

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end	

	def update
      @play.category_id = params[:category_id]

	  if @play.update(play_params)
	     redirect_to play_path(@play)
	    else
	       render 'edit'
	    end 	
	end	

	def destroy
	  @play.destroy
	  redirect_to root_path
	 end	

	private

	def play_params
		params.require(:play).permit(:title, :description, :director, :category_id, :play_img)
	end	

	def find_play
		@play = Play.find(params[:id])
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_play
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]



	def new
		@review = Review.new
	end

	def create
		@play = Play.find(params[:play_id])
		@review = Review.new(review_params)
		@review.play_id = @play.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to play_path(@play)
		else
		   render 'new'   	
	    end	
    end


    def edit	
    end

    def update
    	@review = Review.find(params[:id])
    	if @review.update(review_params)
    		redirect_to play_path(@play)
    	else
    	   render 'edit'
        end	
    end	

    def destroy
        @review.destroy
        redirect_to play_path(@play)	
    end

    private

    def review_params
    	params.require(:review).permit(:rating, :comment)	
    end

    def find_play
    	@play = Play.find(params[:play_id])
    end	

     def find_review
    	@review = Review.find(params[:id])
    end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weed Recipes App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-default">
      	<div class="container">
            <div class="navbar-header">
                <%= link_to "Weed Recipes", root_path, class: "navbar-brand" %>
            </div>
            <ul class="nav navbar-nav navbar-right">
               <% if user_signed_in? %>
                 <li><%= link_to "Sign Out", destroy_user_session_path,method: :delete%></li>
               <% else %>
                 <li><%= link_to "Sign Up", new_user_registration_path %></li>
                 <li><%= link_to "Log In", new_user_session_path %></li>
               <% end %>
            </ul>

	        <ul class="nav navbar-nav">
	          <li class="dropdown">
	             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>

	             <ul class="dropdown-menu" role="menu">
	             	<% Category.all.each do |category| %>
	             	  <li class="<%= 'active' if params[:category] == category.name %>">
	             	  <%= link_to category.name, plays_path(category:category.name), class: "link" %>  
	             	  </li>
	             	 <% end %> 
	             </ul>
	          </li>

	            <% if user_signed_in? %>
	            <li><%= link_to "Add Play", new_play_path %></li>
	            <% end %>
	        </ul>

      	</div>
      </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>  

    <div class="container">
    <%= yield %>
    </div>

  </body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
  <%= f.file_field :play_img %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
  <%= f.input :title, label: "Play Title" %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<div class="col-md-10 col-md-offset-1">
   <div class="new-play-form">
		<h1>Edit Weed Recipe</h1>


		<%= simple_form_for @play, html: {multipart: true} do |f| %>
		  <%= f.file_field :play_img %>
		  <%= f.select :category_id, @categories %>
		  <%= f.input :title, label: "Play Title" %>
		  <%= f.input :description %>
		  <%= f.input :director %>
		  <%= f.button :submit %>
        <% end %>
   </div>
</div>

app/views/plays/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @plays.count == 0 %>
  <h3>There are no plays in this category</h3>
<% else %>  
  <div class="row">
	  <% @plays.each do |play| %>
	  <div class="col-md-3">
	      <a href="/plays/ <%= play.id %>">
	        <%= image_tag play.play_img.url(:play_index), class: "play" %>
	      </a>
	  </div>
  <% end %>
  </div>
<% end %>

app/views/plays/new.html.erb
<div class="col-md-10 col-md-offset-1">
   <div class="new-play-form">
		<h1>New Weed Recipes Post</h1>

		<%= render 'form' %>
	</div>
</div>

app/views/plays/show.html.erb
<div class="row">
    <div class="col-md-4">
         <%= image_tag @play.play_img.url(:play_show), class: "play_show"  %>
    </div>
   
    <div class="col-md-8">
      <div class="play-info">
    	<h1 class="play-title"><%= @play.title %></h1>
		<h4 class="play-director"><span><em>From: </em></span><%= @play.director %></h4>
		<h5 class="play-category"><%= @play.category.name %></h5>
		<h4 class="avg-rating"> Average Rating</h4>
		<div class="average-review-rating" data-score=<%= @average_review %>></div>
		<span class="number-of-reviews"><em>From: </em><%= @play.reviews.count %> reviews </span>
		<p class="play-desc"><%= @play.description %>></p>
    </div>
   </div>
</div>

<div class="row">
     <div class="col-md-12">
     	<div class="reviews">
     		<h1> Reviews </h1>
     		   <%= render @play.reviews %>
     		   <div>
     		   	<%= link_to "Add Reviews", new_play_review_path(@play), class: "btn-custom" %>
     		   </div>
     	</div>
     </div>
</div>
<div class="links btn-group">
  <% if user_signed_in? %>
    <% if @play.user_id == current_user.id %>
	  <%= link_to "Edit", edit_play_path(@play), class: "btn btn-custom" %>
	  <%= link_to "Delete", play_path(@play), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom" %>
   <% end %>
  <% end %>	

</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
   <div id="rating-form">
      <label> Rating </label>
   </div>
   <%= f.input :comment %>
   <%= f.button :submit, :class => "btn-custom2" %>   
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>

	<% if user_signed_in? %>
	  <% if review.user_id == current_user.id %>
	    <div class="links btn-group">
	    <%= link_to "Edit", edit_play_review_path(review.play, review), class: "btn btn-custom" %>
	    <%= link_to "Delete", play_review_path(review.play, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

       </div>
      <% end %>
    <% end %>
</div>       

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
    <div class="edit-review-form">
       <h1> Edit Review </h1>
		<%= simple_form_for([@play, @review]) do |f| %>
		   <div id="rating-form">
		      <label> Rating </label>
		   </div>
		   <%= f.input :comment %>
		   <%= f.button :submit, :class => "btn-custom2" %>   
		<% end %>
   </div>
</div>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="new-review-form">
		<h1> Post Review </h1>
		<%= render 'form' %>
	</div>
</div>